import { StyleSheet } from "react-native";
import { fonts, radius, shadow, spacing, type Palette } from "../src/theme";
// eslint-disable-next-line max-lines-per-function
export const makeStyles = (p: Palette) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: p.cream },
    content: { padding: spacing(3), paddingBottom: spacing(7) },
    hero: {
      backgroundColor: p.burgundyDeep,
      borderRadius: radius.lg,
      padding: spacing(2.5),
      overflow: "hidden",
    },
    watermark: { position: "absolute", right: -14, bottom: -25, opacity: 0.1 },
    eyebrow: {
      color: p.gold,
      fontSize: 10,
      fontWeight: "900",
      letterSpacing: 1.8,
    },
    title: {
      color: p.onAccent,
      fontFamily: fonts.display,
      fontSize: 28,
      fontWeight: "800",
      marginTop: spacing(0.75),
    },
    subtitle: {
      color: "rgba(255,255,255,0.68)",
      fontSize: 14,
      lineHeight: 21,
      marginTop: spacing(0.75),
    },
    paymentNotice: {
      backgroundColor: p.elevated,
      borderColor: p.gold,
      borderRadius: radius.sm,
      borderWidth: 1,
      color: p.ink,
      fontFamily: fonts.body,
      fontSize: 13,
      lineHeight: 19,
      marginBottom: spacing(1.5),
      padding: spacing(1.5),
    },
    section: {
      color: p.ink,
      fontFamily: fonts.display,
      fontSize: 20,
      fontWeight: "800",
      marginTop: spacing(3.5),
      marginBottom: spacing(1.5),
    },
    form: {
      gap: spacing(1),
      backgroundColor: p.white,
      borderRadius: radius.lg,
      padding: spacing(2),
      borderWidth: 1,
      borderColor: p.softBorder,
    },
    input: {
      minHeight: 48,
      borderWidth: 1,
      borderColor: p.softBorder,
      borderRadius: radius.sm,
      paddingHorizontal: spacing(1.5),
      color: p.ink,
      backgroundColor: p.panel,
    },
    group: {
      backgroundColor: p.white,
      borderRadius: radius.lg,
      padding: spacing(2),
      borderWidth: 1,
      borderColor: p.softBorder,
      ...shadow.card,
    },
    groupHead: {
      flexDirection: "row",
      alignItems: "baseline",
      justifyContent: "space-between",
      gap: spacing(1),
    },
    store: {
      flex: 1,
      color: p.ink,
      fontFamily: fonts.display,
      fontSize: 19,
      fontWeight: "800",
    },
    total: { color: p.burgundy, fontSize: 14, fontWeight: "900" },
    item: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing(1.25),
      paddingVertical: spacing(1.25),
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: p.softBorder,
    },
    image: {
      width: 54,
      height: 62,
      borderRadius: radius.sm,
      backgroundColor: p.wineTint,
    },
    itemCopy: { flex: 1 },
    itemTitle: { color: p.ink, fontSize: 14, fontWeight: "800" },
    itemHint: { color: p.mutedText, fontSize: 11, marginTop: 3 },
    quantity: { flexDirection: "row", alignItems: "center", gap: spacing(1) },
    quantityButton: {
      width: 30,
      height: 30,
      borderRadius: radius.pill,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: p.sunken,
    },
    quantityText: { color: p.ink, fontWeight: "900" },
    selector: {
      flexDirection: "row",
      gap: spacing(1),
      marginTop: spacing(1.5),
    },
    chip: {
      flex: 1,
      alignItems: "center",
      paddingVertical: spacing(1),
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: p.softBorder,
    },
    chipActive: { backgroundColor: p.wineTint, borderColor: p.burgundy },
    chipText: { color: p.mutedText, fontSize: 12, fontWeight: "800" },
    chipTextActive: { color: p.burgundy },
    zone: {
      marginTop: spacing(1),
      minHeight: 44,
      borderWidth: 1,
      borderColor: p.softBorder,
      borderRadius: radius.sm,
      paddingHorizontal: spacing(1.5),
      color: p.ink,
    },
    checkout: {
      minHeight: 50,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: radius.pill,
      backgroundColor: p.burgundy,
      marginTop: spacing(1.5),
    },
    checkoutDisabled: { opacity: 0.45 },
    checkoutText: { color: p.onAccent, fontSize: 14, fontWeight: "900" },
    empty: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      padding: spacing(4),
    },
    emptyIcon: {
      width: 76,
      height: 76,
      borderRadius: radius.lg,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: p.wineTint,
    },
    emptyTitle: {
      color: p.ink,
      fontFamily: fonts.display,
      fontSize: 23,
      fontWeight: "800",
      marginTop: spacing(2),
    },
    emptyHint: {
      color: p.mutedText,
      fontSize: 14,
      textAlign: "center",
      lineHeight: 21,
      marginTop: spacing(0.75),
    },
    browse: {
      marginTop: spacing(2),
      paddingHorizontal: spacing(3),
      paddingVertical: spacing(1.5),
      borderRadius: radius.pill,
      backgroundColor: p.burgundy,
    },
    browseText: { color: p.onAccent, fontWeight: "800" },
    error: { color: p.danger, fontSize: 12, marginTop: spacing(1) },
  });
