import { StyleSheet } from "react-native";

import {
  fonts,
  radius,
  spacing,
  type Palette,
  typeScale,
} from "../../src/theme";

// Style maps are declarative tokens rather than executable screen logic.
// eslint-disable-next-line max-lines-per-function
export const makeStyles = (palette: Palette) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: palette.cream },
    content: { padding: spacing(2.5), paddingBottom: spacing(7) },
    signOut: { color: palette.onAccent, fontSize: 13, fontWeight: "700" },
    hero: {
      backgroundColor: palette.burgundyDeep,
      borderRadius: radius.lg,
      padding: spacing(2.5),
      overflow: "hidden",
    },
    heroTop: {
      flexDirection: "row",
      alignItems: "flex-start",
      gap: spacing(2),
    },
    heroCopy: { flex: 1 },
    heroIcon: {
      width: 48,
      height: 48,
      borderRadius: radius.md,
      backgroundColor: "rgba(255,255,255,0.09)",
      alignItems: "center",
      justifyContent: "center",
    },
    eyebrow: {
      color: palette.gold,
      fontSize: 10,
      fontWeight: "900",
      letterSpacing: 1.7,
    },
    heroTitle: {
      ...typeScale.title,
      color: palette.onAccent,
      fontFamily: fonts.display,
      fontWeight: "800",
      marginTop: spacing(0.5),
    },
    heroHint: {
      color: "rgba(255,255,255,0.66)",
      lineHeight: 20,
      marginTop: spacing(0.75),
    },
    balanceLabel: {
      color: "rgba(255,255,255,0.62)",
      fontSize: 12,
      marginTop: spacing(3),
    },
    balance: {
      color: palette.onAccent,
      fontSize: 36,
      lineHeight: 43,
      fontWeight: "900",
      letterSpacing: -1,
    },
    heroStats: {
      flexDirection: "row",
      gap: spacing(2),
      marginTop: spacing(2),
      paddingTop: spacing(2),
      borderTopWidth: 1,
      borderTopColor: "rgba(255,255,255,0.12)",
    },
    banner: {
      backgroundColor: `${palette.warning}16`,
      borderRadius: radius.sm,
      padding: spacing(1.5),
      marginTop: spacing(2),
    },
    bannerText: { color: palette.warning, lineHeight: 19, fontWeight: "600" },
    sectionTitle: {
      ...typeScale.heading,
      color: palette.ink,
      fontFamily: fonts.display,
      fontWeight: "800",
      marginTop: spacing(3),
    },
    metricGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: spacing(1.25),
      marginTop: spacing(1.25),
    },
    metric: {
      width: "48%",
      flexGrow: 1,
      minHeight: 118,
      borderRadius: radius.md,
      backgroundColor: palette.elevated,
      borderWidth: 1,
      borderColor: palette.hairline,
      padding: spacing(1.75),
    },
    metricValue: {
      color: palette.ink,
      fontSize: 23,
      fontWeight: "900",
      marginTop: spacing(1),
    },
    metricLabel: { color: palette.mutedText, fontSize: 12, marginTop: 2 },
    shareCard: {
      marginTop: spacing(1.25),
      borderRadius: radius.lg,
      backgroundColor: palette.wineTint,
      padding: spacing(2),
      borderWidth: 1,
      borderColor: palette.hairline,
    },
    shareHeading: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing(1.25),
    },
    shareIcon: {
      width: 42,
      height: 42,
      borderRadius: radius.md,
      backgroundColor: palette.elevated,
      alignItems: "center",
      justifyContent: "center",
    },
    shareCode: {
      color: palette.ink,
      fontSize: 18,
      fontWeight: "900",
      letterSpacing: 0.4,
    },
    shareWindow: { color: palette.mutedText, fontSize: 12, marginTop: 2 },
    url: {
      color: palette.mutedText,
      fontSize: 13,
      lineHeight: 19,
      marginTop: spacing(1.5),
    },
    shareButton: {
      minHeight: 48,
      borderRadius: radius.pill,
      backgroundColor: palette.burgundy,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: spacing(1),
      marginTop: spacing(1.5),
    },
    shareButtonText: { color: palette.onAccent, fontWeight: "800" },
    sectionHead: {
      flexDirection: "row",
      alignItems: "baseline",
      justifyContent: "space-between",
    },
    sectionAction: { color: palette.burgundy, fontSize: 13, fontWeight: "800" },
    listCard: {
      marginTop: spacing(1.25),
      borderRadius: radius.md,
      backgroundColor: palette.elevated,
      borderWidth: 1,
      borderColor: palette.hairline,
      overflow: "hidden",
    },
    row: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing(1.25),
      padding: spacing(1.75),
    },
    rowBorder: { borderTopWidth: 1, borderTopColor: palette.hairline },
    rowIcon: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: palette.wineTint,
      alignItems: "center",
      justifyContent: "center",
    },
    rowTitle: { color: palette.ink, fontWeight: "800" },
    rowMeta: { color: palette.mutedText, fontSize: 12, marginTop: 3 },
    rowAmount: { color: palette.ink, fontWeight: "900" },
    quickGrid: {
      flexDirection: "row",
      gap: spacing(1.25),
      marginTop: spacing(3),
    },
    quick: {
      flex: 1,
      borderRadius: radius.md,
      padding: spacing(2),
      backgroundColor: palette.ink,
    },
    quickTitle: {
      color: palette.onAccent,
      fontWeight: "900",
      fontSize: 16,
      marginTop: spacing(1),
    },
    quickSubtitle: {
      color: "rgba(255,255,255,0.58)",
      fontSize: 12,
      marginTop: 3,
    },
    pressed: { transform: [{ scale: 0.975 }], opacity: 0.92 },
  });
