import { reactRouter } from "@react-router/dev/vite";
import { defineConfig } from "vite";

const muiComponents = [
  "Alert",
  "Box",
  "Button",
  "Checkbox",
  "Chip",
  "Container",
  "CssBaseline",
  "Divider",
  "Drawer",
  "FormControl",
  "FormControlLabel",
  "InputAdornment",
  "List",
  "ListItemButton",
  "ListItemIcon",
  "ListItemText",
  "MenuItem",
  "Paper",
  "Select",
  "Skeleton",
  "Snackbar",
  "Stack",
  "Tab",
  "Tabs",
  "TextField",
  "Toolbar",
  "Typography",
].map((name) => `@mui/material/${name}`);

const muiIcons = [
  "AdminPanelSettingsRounded",
  "AccountBalanceRounded",
  "ArrowForwardRounded",
  "AssignmentTurnedInRounded",
  "BlockRounded",
  "CancelRounded",
  "CheckCircleRounded",
  "EmailRounded",
  "FileDownloadRounded",
  "HistoryRounded",
  "LockRounded",
  "LogoutRounded",
  "NotesRounded",
  "NotificationsActiveRounded",
  "PaymentsRounded",
  "PersonSearchRounded",
  "ReceiptLongRounded",
  "SearchRounded",
  "SettingsRounded",
  "ShieldRounded",
  "StorefrontRounded",
  "SupportAgentRounded",
  "SyncRounded",
  "TrendingUpRounded",
  "VerifiedUserRounded",
  "WarningAmberRounded",
].map((name) => `@mui/icons-material/${name}`);

export default defineConfig({
  plugins: [reactRouter()],
  server: {
    host: "127.0.0.1",
    port: 3403,
  },
  resolve: {
    dedupe: [
      "react",
      "react-dom",
      "@emotion/react",
      "@emotion/styled",
      "@emotion/cache",
    ],
  },
  optimizeDeps: {
    include: [
      "react",
      "react-dom",
      "react-dom/client",
      "react-router",
      "react-router/dom",
      "@emotion/react",
      "@emotion/styled",
      "@emotion/cache",
      "@mui/material/styles",
      ...muiComponents,
      ...muiIcons,
    ],
  },
  ssr: {
    noExternal: [
      /^@mui\//,
      "@emotion/react",
      "@emotion/styled",
      "@emotion/cache",
      "@emotion/server",
      "@xtiitch/design-tokens",
      "react-transition-group",
    ],
  },
});
