import { StyleSheet } from "react-native";
import { fonts, radius, shadow, spacing, type Palette } from "../../src/theme";

export const makeStyles = (p: Palette) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: p.cream },
    content: { padding: spacing(3), paddingBottom: spacing(7) },
    hero: {
      backgroundColor: p.burgundyDeep,
      borderRadius: radius.lg,
      overflow: "hidden",
      padding: spacing(2.5),
    },
    watermark: { position: "absolute", right: -18, bottom: -28, opacity: 0.1 },
    eyebrow: {
      color: p.gold,
      fontFamily: fonts.body,
      fontSize: 10,
      fontWeight: "900",
      letterSpacing: 1.8,
    },
    title: {
      color: p.onAccent,
      fontFamily: fonts.display,
      fontSize: 28,
      fontWeight: "800",
      marginTop: spacing(0.75),
    },
    subtitle: {
      color: "rgba(255,255,255,0.68)",
      fontFamily: fonts.body,
      fontSize: 14,
      lineHeight: 21,
      marginTop: spacing(0.75),
    },
    section: {
      color: p.ink,
      fontFamily: fonts.display,
      fontSize: 20,
      fontWeight: "800",
      marginTop: spacing(3),
      marginBottom: spacing(1.25),
    },
    card: {
      backgroundColor: p.white,
      borderColor: p.softBorder,
      borderRadius: radius.md,
      borderWidth: 1,
      gap: spacing(1.25),
      padding: spacing(2),
      ...shadow.card,
    },
    cardTitle: {
      color: p.ink,
      fontFamily: fonts.display,
      fontSize: 18,
      fontWeight: "800",
    },
    input: {
      backgroundColor: p.sunken,
      borderColor: p.softBorder,
      borderRadius: radius.sm,
      borderWidth: 1,
      color: p.ink,
      flex: 1,
      fontFamily: fonts.body,
      fontSize: 15,
      paddingHorizontal: spacing(1.5),
      paddingVertical: spacing(1.3),
    },
    inline: { alignItems: "center", flexDirection: "row", gap: spacing(1) },
    hint: {
      color: p.mutedText,
      fontFamily: fonts.body,
      fontSize: 13,
      lineHeight: 19,
    },
    good: {
      color: p.success,
      fontFamily: fonts.body,
      fontSize: 13,
      fontWeight: "800",
    },
    primary: {
      alignItems: "center",
      backgroundColor: p.burgundy,
      borderRadius: radius.pill,
      paddingVertical: spacing(1.4),
    },
    primaryText: {
      color: p.onAccent,
      fontFamily: fonts.body,
      fontSize: 14,
      fontWeight: "900",
    },
    secondary: {
      alignItems: "center",
      borderColor: p.burgundy,
      borderRadius: radius.pill,
      borderWidth: 1.5,
      paddingHorizontal: spacing(1.5),
      paddingVertical: spacing(1.15),
    },
    secondaryText: {
      color: p.burgundy,
      fontFamily: fonts.body,
      fontSize: 13,
      fontWeight: "800",
    },
    photoRow: { flexDirection: "row", gap: spacing(1) },
    photoButton: {
      alignItems: "center",
      backgroundColor: p.sunken,
      borderColor: p.softBorder,
      borderRadius: radius.sm,
      borderStyle: "dashed",
      borderWidth: 1,
      flex: 1,
      height: 100,
      justifyContent: "center",
      overflow: "hidden",
    },
    photo: { height: "100%", width: "100%" },
  });
