import { StyleSheet } from "react-native";

import { fonts, radius, shadow, spacing, type Palette } from "../../src/theme";

// Style maps are declarative tokens rather than executable screen logic.
// eslint-disable-next-line max-lines-per-function
export const styles = (p: Palette) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: p.cream },
    content: { padding: spacing(3), paddingBottom: spacing(7) },
    hero: {
      backgroundColor: p.burgundyDeep,
      borderRadius: radius.lg,
      overflow: "hidden",
      padding: spacing(2.5),
    },
    watermark: { position: "absolute", right: -12, bottom: -30, opacity: 0.1 },
    eyebrow: {
      color: p.gold,
      fontFamily: fonts.body,
      fontSize: 10,
      fontWeight: "900",
      letterSpacing: 1.8,
    },
    title: {
      color: p.onAccent,
      fontFamily: fonts.display,
      fontSize: 28,
      fontWeight: "800",
      marginTop: spacing(0.75),
    },
    subtitle: {
      color: "rgba(255,255,255,0.68)",
      fontFamily: fonts.body,
      fontSize: 14,
      lineHeight: 21,
      marginTop: spacing(0.75),
    },
    section: {
      color: p.ink,
      fontFamily: fonts.display,
      fontSize: 20,
      fontWeight: "800",
      marginTop: spacing(3),
      marginBottom: spacing(1.25),
    },
    card: {
      backgroundColor: p.white,
      borderColor: p.softBorder,
      borderRadius: radius.md,
      borderWidth: 1,
      gap: spacing(1),
      padding: spacing(1.75),
      ...shadow.card,
    },
    list: { gap: spacing(1) },
    programmeRow: {
      alignItems: "center",
      backgroundColor: p.white,
      borderColor: p.softBorder,
      borderRadius: radius.md,
      borderWidth: 1,
      flexDirection: "row",
      gap: spacing(1),
      marginTop: spacing(1),
      padding: spacing(1.5),
    },
    input: {
      backgroundColor: p.sunken,
      borderColor: p.softBorder,
      borderRadius: radius.sm,
      borderWidth: 1,
      color: p.ink,
      fontFamily: fonts.body,
      fontSize: 14,
      paddingHorizontal: spacing(1.25),
      paddingVertical: spacing(1.2),
    },
    primary: {
      alignItems: "center",
      backgroundColor: p.burgundy,
      borderRadius: radius.pill,
      paddingVertical: spacing(1.3),
    },
    primaryText: {
      color: p.onAccent,
      fontFamily: fonts.body,
      fontSize: 13,
      fontWeight: "900",
    },
    chips: { flexDirection: "row", flexWrap: "wrap", gap: spacing(0.7) },
    chip: {
      backgroundColor: p.sunken,
      borderRadius: radius.pill,
      paddingHorizontal: spacing(1.2),
      paddingVertical: spacing(0.8),
    },
    chipActive: { backgroundColor: p.burgundy },
    chipText: {
      color: p.ink,
      fontFamily: fonts.body,
      fontSize: 12,
      fontWeight: "800",
    },
    chipTextActive: { color: p.onAccent },
    row: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
    },
    copy: { flex: 1 },
    cardTitle: {
      color: p.ink,
      fontFamily: fonts.display,
      fontSize: 18,
      fontWeight: "800",
    },
    hint: {
      color: p.mutedText,
      fontFamily: fonts.body,
      fontSize: 12,
      lineHeight: 18,
    },
    status: {
      color: p.burgundy,
      fontFamily: fonts.body,
      fontSize: 10,
      fontWeight: "900",
      textTransform: "uppercase",
    },
    metrics: { flexDirection: "row", flexWrap: "wrap", gap: spacing(0.7) },
    metric: {
      backgroundColor: p.wineTint,
      borderRadius: radius.pill,
      color: p.burgundy,
      fontFamily: fonts.body,
      fontSize: 11,
      fontWeight: "800",
      overflow: "hidden",
      paddingHorizontal: spacing(1),
      paddingVertical: spacing(0.6),
    },
    secondary: {
      alignSelf: "flex-start",
      borderColor: p.burgundy,
      borderRadius: radius.pill,
      borderWidth: 1,
      paddingHorizontal: spacing(1.2),
      paddingVertical: spacing(0.8),
    },
    secondaryText: {
      color: p.burgundy,
      fontFamily: fonts.body,
      fontSize: 11,
      fontWeight: "900",
    },
  });
