import { StyleSheet } from "react-native";

import { fonts, radius, spacing, type Palette } from "../../src/theme";

// eslint-disable-next-line max-lines-per-function -- one centralized theme-aware screen stylesheet
export const makeStyles = (palette: Palette) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: palette.cream },
    content: { padding: spacing(3), paddingBottom: spacing(6) },
    signOut: {
      color: palette.onAccent,
      fontFamily: fonts.body,
      fontWeight: "700",
      fontSize: 14,
    },
    greeting: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing(1.75),
      marginBottom: spacing(2.5),
      backgroundColor: palette.burgundyDeep,
      borderRadius: radius.lg,
      padding: spacing(2.25),
    },
    greetingMark: {
      width: 54,
      height: 54,
      borderRadius: radius.md,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "rgba(255,255,255,0.09)",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.12)",
    },
    greetingCopy: { flex: 1 },
    eyebrow: {
      color: palette.gold,
      fontFamily: fonts.body,
      fontSize: 10,
      fontWeight: "900",
      letterSpacing: 1.8,
    },
    hello: {
      fontFamily: fonts.display,
      fontSize: 28,
      color: palette.onAccent,
      fontWeight: "700",
    },
    role: {
      fontFamily: fonts.body,
      fontSize: 13,
      color: "rgba(255,255,255,0.68)",
      textTransform: "capitalize",
      marginTop: spacing(0.25),
    },
    kpiRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing(1.5) },
    kpi: {
      flexGrow: 1,
      flexBasis: "30%",
      backgroundColor: palette.white,
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: palette.softBorder,
      padding: spacing(2),
    },
    kpiWide: { flexBasis: "100%" },
    newOrderCta: {
      backgroundColor: palette.burgundy,
      borderRadius: radius.pill,
      paddingVertical: spacing(1.75),
      alignItems: "center",
      marginTop: spacing(2),
    },
    newOrderCtaText: {
      color: palette.onAccent,
      fontFamily: fonts.body,
      fontSize: 15,
      fontWeight: "800",
    },
    kpiValue: {
      fontFamily: fonts.display,
      fontSize: 26,
      fontWeight: "700",
      color: palette.ink,
    },
    kpiLabel: {
      fontFamily: fonts.body,
      fontSize: 12,
      fontWeight: "700",
      letterSpacing: 0.6,
      textTransform: "uppercase",
      color: palette.mutedText,
      marginTop: spacing(0.5),
    },
    sectionHead: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: spacing(3.5),
      marginBottom: spacing(1.5),
    },
    sectionLabel: {
      fontFamily: fonts.body,
      fontSize: 12,
      fontWeight: "800",
      letterSpacing: 1.5,
      textTransform: "uppercase",
      color: palette.mutedText,
    },
    viewAll: {
      fontFamily: fonts.body,
      fontSize: 14,
      fontWeight: "700",
      color: palette.burgundy,
    },
    orderList: { gap: spacing(1.5) },
    menuGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing(1.5) },
    menuItem: {
      flexGrow: 1,
      flexBasis: "44%",
      backgroundColor: palette.white,
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: palette.softBorder,
      padding: spacing(2),
      minHeight: 150,
      overflow: "hidden",
    },
    menuIcon: {
      width: 40,
      height: 40,
      borderRadius: radius.sm,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: palette.wineTint,
      marginBottom: spacing(1.5),
    },
    menuArrow: {
      position: "absolute",
      right: spacing(1.5),
      bottom: spacing(1.5),
    },
    menuTitle: {
      fontFamily: fonts.body,
      fontSize: 15,
      fontWeight: "800",
      color: palette.ink,
    },
    menuHint: {
      fontFamily: fonts.body,
      fontSize: 12,
      color: palette.mutedText,
      marginTop: spacing(0.5),
    },
    empty: {
      backgroundColor: palette.panel,
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: palette.softBorder,
      padding: spacing(3),
      alignItems: "center",
    },
    emptyTitle: { fontFamily: fonts.display, fontSize: 18, color: palette.ink },
    emptyHint: {
      fontFamily: fonts.body,
      fontSize: 14,
      color: palette.mutedText,
      textAlign: "center",
      marginTop: spacing(0.75),
      lineHeight: 20,
    },
  });
