import { StyleSheet } from "react-native";

import { fonts, radius, shadow, spacing, type Palette } from "../../src/theme";

// eslint-disable-next-line max-lines-per-function -- centralized theme-aware screen stylesheet
export const makeStyles = (palette: Palette) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: palette.cream },
    content: { padding: spacing(3), paddingBottom: spacing(7) },
    hero: {
      backgroundColor: palette.burgundyDeep,
      borderRadius: radius.lg,
      padding: spacing(2.5),
      overflow: "hidden",
    },
    eyebrow: {
      color: palette.gold,
      fontFamily: fonts.body,
      fontSize: 10,
      fontWeight: "900",
      letterSpacing: 1.8,
    },
    title: {
      color: palette.onAccent,
      fontFamily: fonts.display,
      fontSize: 28,
      fontWeight: "800",
      marginTop: spacing(0.75),
    },
    subtitle: {
      color: "rgba(255,255,255,0.68)",
      fontFamily: fonts.body,
      fontSize: 14,
      lineHeight: 21,
      marginTop: spacing(0.75),
      maxWidth: 310,
    },
    watermark: { position: "absolute", right: -18, bottom: -28, opacity: 0.1 },
    statRow: {
      flexDirection: "row",
      gap: spacing(1.25),
      marginTop: spacing(2),
    },
    primaryAction: {
      alignItems: "center",
      alignSelf: "flex-start",
      backgroundColor: palette.burgundy,
      borderRadius: radius.pill,
      flexDirection: "row",
      gap: spacing(0.75),
      marginTop: spacing(2),
      paddingHorizontal: spacing(2),
      paddingVertical: spacing(1.25),
    },
    primaryActionText: {
      color: palette.onAccent,
      fontFamily: fonts.body,
      fontSize: 14,
      fontWeight: "800",
    },
    secondaryAction: {
      alignItems: "center",
      alignSelf: "flex-start",
      borderColor: palette.burgundy,
      borderRadius: radius.pill,
      borderWidth: 1.5,
      flexDirection: "row",
      gap: spacing(0.75),
      marginTop: spacing(1),
      paddingHorizontal: spacing(2),
      paddingVertical: spacing(1.1),
    },
    secondaryActionText: {
      color: palette.burgundy,
      fontFamily: fonts.body,
      fontSize: 13,
      fontWeight: "800",
    },
    stat: {
      flex: 1,
      backgroundColor: palette.white,
      borderRadius: radius.md,
      padding: spacing(1.75),
      borderWidth: 1,
      borderColor: palette.softBorder,
    },
    statValue: {
      color: palette.ink,
      fontFamily: fonts.display,
      fontSize: 24,
      fontWeight: "800",
    },
    statLabel: {
      color: palette.mutedText,
      fontFamily: fonts.body,
      fontSize: 11,
      fontWeight: "700",
      marginTop: 2,
    },
    sectionTitle: {
      color: palette.ink,
      fontFamily: fonts.display,
      fontSize: 21,
      fontWeight: "800",
      marginTop: spacing(3.5),
      marginBottom: spacing(1.5),
    },
    collectionRow: { gap: spacing(1), paddingRight: spacing(2) },
    collectionChip: {
      paddingHorizontal: spacing(1.75),
      paddingVertical: spacing(1.1),
      backgroundColor: palette.white,
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: palette.softBorder,
    },
    collectionChipRetired: { opacity: 0.52 },
    collectionText: {
      color: palette.ink,
      fontFamily: fonts.body,
      fontSize: 13,
      fontWeight: "700",
    },
    list: { gap: spacing(1.5) },
    card: {
      flexDirection: "row",
      backgroundColor: palette.white,
      borderRadius: radius.md,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: palette.softBorder,
      ...shadow.card,
    },
    image: { width: 104, minHeight: 132, backgroundColor: palette.wineTint },
    imageFallback: {
      width: 104,
      minHeight: 132,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: palette.wineTint,
    },
    body: { flex: 1, padding: spacing(1.75) },
    cardActions: { flexDirection: "row", gap: spacing(0.75) },
    cardTop: {
      flexDirection: "row",
      gap: spacing(1),
      alignItems: "flex-start",
    },
    cardTitle: {
      flex: 1,
      color: palette.ink,
      fontFamily: fonts.display,
      fontSize: 17,
      fontWeight: "800",
    },
    status: {
      borderRadius: radius.pill,
      paddingHorizontal: spacing(1),
      paddingVertical: 4,
      backgroundColor: palette.wineTint,
    },
    statusRetired: { backgroundColor: palette.sunken },
    statusText: {
      color: palette.burgundy,
      fontFamily: fonts.body,
      fontSize: 10,
      fontWeight: "900",
      textTransform: "uppercase",
    },
    meta: {
      color: palette.mutedText,
      fontFamily: fonts.body,
      fontSize: 12,
      lineHeight: 18,
      marginTop: spacing(0.75),
    },
    action: {
      alignSelf: "flex-start",
      marginTop: spacing(1.25),
      paddingVertical: spacing(0.75),
      paddingHorizontal: spacing(1.25),
      borderRadius: radius.pill,
      backgroundColor: palette.wineTint,
    },
    actionText: {
      color: palette.burgundy,
      fontFamily: fonts.body,
      fontSize: 12,
      fontWeight: "800",
    },
    pressed: { opacity: 0.74, transform: [{ scale: 0.985 }] },
    empty: {
      alignItems: "center",
      padding: spacing(4),
      borderRadius: radius.lg,
      backgroundColor: palette.panel,
      borderWidth: 1,
      borderColor: palette.softBorder,
    },
    emptyTitle: {
      color: palette.ink,
      fontFamily: fonts.display,
      fontSize: 19,
      fontWeight: "800",
      marginTop: spacing(1.5),
    },
    emptyHint: {
      color: palette.mutedText,
      fontFamily: fonts.body,
      fontSize: 14,
      lineHeight: 20,
      textAlign: "center",
      marginTop: spacing(0.75),
    },
  });
