import { StyleSheet } from "react-native";
import { fonts, radius, shadow, spacing, type Palette } from "../../src/theme";

// One palette factory keeps editor, media, and variation subviews synchronized.
// eslint-disable-next-line max-lines-per-function
export const makeStyles = (p: Palette) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: p.cream },
    content: { padding: spacing(3), paddingBottom: spacing(7) },
    hero: {
      backgroundColor: p.burgundyDeep,
      borderRadius: radius.lg,
      padding: spacing(2.5),
      overflow: "hidden",
    },
    watermark: { position: "absolute", right: -15, bottom: -28, opacity: 0.1 },
    eyebrow: {
      color: p.gold,
      fontFamily: fonts.body,
      fontSize: 10,
      fontWeight: "900",
      letterSpacing: 1.8,
    },
    title: {
      color: p.onAccent,
      fontFamily: fonts.display,
      fontSize: 28,
      fontWeight: "800",
      marginTop: spacing(0.75),
    },
    subtitle: {
      color: "rgba(255,255,255,0.68)",
      fontFamily: fonts.body,
      fontSize: 14,
      lineHeight: 21,
      marginTop: spacing(0.75),
    },
    section: {
      color: p.ink,
      fontFamily: fonts.display,
      fontSize: 20,
      fontWeight: "800",
      marginTop: spacing(3),
      marginBottom: spacing(1.25),
    },
    card: {
      backgroundColor: p.white,
      borderColor: p.softBorder,
      borderRadius: radius.md,
      borderWidth: 1,
      gap: spacing(1.25),
      padding: spacing(2),
      ...shadow.card,
    },
    label: {
      color: p.mutedText,
      fontFamily: fonts.body,
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    input: {
      backgroundColor: p.sunken,
      borderColor: p.softBorder,
      borderRadius: radius.sm,
      borderWidth: 1,
      color: p.ink,
      fontFamily: fonts.body,
      fontSize: 15,
      paddingHorizontal: spacing(1.5),
      paddingVertical: spacing(1.35),
    },
    multiline: { minHeight: 96, textAlignVertical: "top" },
    row: { flexDirection: "row", flexWrap: "wrap", gap: spacing(0.75) },
    chip: {
      backgroundColor: p.sunken,
      borderRadius: radius.pill,
      paddingHorizontal: spacing(1.25),
      paddingVertical: spacing(0.9),
    },
    chipActive: { backgroundColor: p.burgundy },
    chipText: {
      color: p.ink,
      fontFamily: fonts.body,
      fontSize: 12,
      fontWeight: "700",
    },
    chipTextActive: { color: p.onAccent },
    switchRow: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
    },
    hint: {
      color: p.mutedText,
      fontFamily: fonts.body,
      fontSize: 12,
      lineHeight: 18,
    },
    priceRow: { alignItems: "center", flexDirection: "row", gap: spacing(1) },
    priceLabel: {
      color: p.ink,
      flex: 1,
      fontFamily: fonts.body,
      fontSize: 14,
      fontWeight: "700",
    },
    priceInput: { minWidth: 120, textAlign: "right" },
    error: {
      color: p.danger,
      fontFamily: fonts.body,
      fontSize: 13,
      marginTop: spacing(1.5),
    },
    save: {
      alignItems: "center",
      backgroundColor: p.burgundy,
      borderRadius: radius.pill,
      marginTop: spacing(2),
      paddingVertical: spacing(1.65),
    },
    saveDisabled: { opacity: 0.45 },
    saveText: {
      color: p.onAccent,
      fontFamily: fonts.body,
      fontSize: 15,
      fontWeight: "900",
    },
    mediaGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing(1) },
    mediaTile: {
      borderRadius: radius.sm,
      height: 104,
      overflow: "hidden",
      width: 84,
    },
    mediaImage: { height: "100%", width: "100%" },
    mediaRemove: {
      alignItems: "center",
      backgroundColor: p.burgundy,
      borderRadius: radius.pill,
      height: 26,
      justifyContent: "center",
      position: "absolute",
      right: 5,
      top: 5,
      width: 26,
    },
    mediaAdd: {
      alignItems: "center",
      borderColor: p.burgundy,
      borderRadius: radius.sm,
      borderStyle: "dashed",
      borderWidth: 1.5,
      height: 104,
      justifyContent: "center",
      width: 84,
    },
    mediaAddText: {
      color: p.burgundy,
      fontFamily: fonts.body,
      fontSize: 11,
      fontWeight: "800",
      marginTop: 4,
    },
    variationRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: spacing(1),
    },
    variationCard: { gap: spacing(1) },
    variationSwatch: {
      backgroundColor: p.wineTint,
      borderRadius: radius.pill,
      height: 34,
      width: 34,
    },
    variationCopy: { flex: 1 },
    variationInput: { flex: 1 },
    smallAction: {
      borderColor: p.burgundy,
      borderRadius: radius.pill,
      borderWidth: 1,
      paddingHorizontal: spacing(1.25),
      paddingVertical: spacing(0.9),
    },
    smallActionText: {
      color: p.burgundy,
      fontFamily: fonts.body,
      fontSize: 12,
      fontWeight: "900",
    },
    iconAction: {
      alignItems: "center",
      borderColor: p.softBorder,
      borderRadius: radius.pill,
      borderWidth: 1,
      height: 30,
      justifyContent: "center",
      width: 30,
    },
  });
