import { StyleSheet } from "react-native";
import { fonts, radius, shadow, spacing, type Palette } from "../../src/theme";

export const makeStyles = (p: Palette) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: p.cream },
    content: { padding: spacing(3), paddingBottom: spacing(7) },
    hero: {
      backgroundColor: p.burgundyDeep,
      borderRadius: radius.lg,
      padding: spacing(2.5),
      overflow: "hidden",
    },
    watermark: { position: "absolute", right: -15, bottom: -28, opacity: 0.1 },
    eyebrow: {
      color: p.gold,
      fontSize: 10,
      fontWeight: "900",
      letterSpacing: 1.8,
    },
    title: {
      color: p.onAccent,
      fontFamily: fonts.display,
      fontSize: 27,
      fontWeight: "800",
      marginTop: spacing(0.75),
    },
    subtitle: {
      color: "rgba(255,255,255,0.68)",
      fontSize: 14,
      lineHeight: 21,
      marginTop: spacing(0.75),
      maxWidth: 300,
    },
    sectionTitle: {
      color: p.ink,
      fontFamily: fonts.display,
      fontSize: 20,
      fontWeight: "800",
      marginTop: spacing(3.5),
      marginBottom: spacing(1.5),
    },
    form: {
      backgroundColor: p.white,
      borderRadius: radius.lg,
      padding: spacing(2),
      borderWidth: 1,
      borderColor: p.softBorder,
      ...shadow.card,
    },
    formRow: { flexDirection: "row", gap: spacing(1) },
    input: {
      flex: 1,
      minHeight: 48,
      borderWidth: 1,
      borderColor: p.softBorder,
      borderRadius: radius.sm,
      paddingHorizontal: spacing(1.5),
      color: p.ink,
      backgroundColor: p.panel,
      fontSize: 15,
    },
    shortInput: { flex: 0, width: 78 },
    actionRow: {
      flexDirection: "row",
      gap: spacing(1),
      marginTop: spacing(1.25),
    },
    button: {
      flex: 1,
      minHeight: 46,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: radius.pill,
      backgroundColor: p.burgundy,
    },
    buttonSecondary: { backgroundColor: p.wineTint },
    buttonDisabled: { opacity: 0.48 },
    buttonText: { color: p.onAccent, fontSize: 14, fontWeight: "800" },
    secondaryText: { color: p.burgundy },
    list: { gap: spacing(1.25) },
    row: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing(1.5),
      backgroundColor: p.white,
      borderRadius: radius.md,
      padding: spacing(1.75),
      borderWidth: 1,
      borderColor: p.softBorder,
    },
    sequence: {
      width: 38,
      height: 38,
      borderRadius: radius.sm,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: p.wineTint,
    },
    sequenceText: { color: p.burgundy, fontWeight: "900" },
    copy: { flex: 1 },
    label: { color: p.ink, fontSize: 15, fontWeight: "800" },
    unit: { color: p.mutedText, fontSize: 12, marginTop: 2 },
    iconAction: {
      width: 38,
      height: 38,
      borderRadius: radius.pill,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: p.sunken,
    },
    empty: {
      padding: spacing(3),
      alignItems: "center",
      backgroundColor: p.panel,
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: p.softBorder,
    },
    emptyTitle: {
      color: p.ink,
      fontFamily: fonts.display,
      fontSize: 18,
      fontWeight: "800",
      marginTop: spacing(1),
    },
    emptyHint: {
      color: p.mutedText,
      fontSize: 13,
      textAlign: "center",
      lineHeight: 19,
      marginTop: spacing(0.5),
    },
    sizeBandLink: {
      alignItems: "center",
      alignSelf: "flex-start",
      backgroundColor: p.burgundy,
      borderRadius: radius.pill,
      flexDirection: "row",
      gap: spacing(0.75),
      marginTop: spacing(1.5),
      paddingHorizontal: spacing(1.5),
      paddingVertical: spacing(1.1),
    },
  });
