import { StyleSheet } from "react-native";
import { fonts, radius, shadow, spacing, type Palette } from "../../src/theme";
// eslint-disable-next-line max-lines-per-function -- complete analytics palette
export const makeStyles = (p: Palette) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: p.cream },
    content: { padding: spacing(3), paddingBottom: spacing(7) },
    hero: {
      backgroundColor: p.ink,
      borderRadius: radius.lg,
      padding: spacing(2.5),
      overflow: "hidden",
    },
    watermark: { position: "absolute", right: -16, bottom: -22, opacity: 0.08 },
    eyebrow: {
      color: p.gold,
      fontSize: 10,
      fontWeight: "900",
      letterSpacing: 1.8,
    },
    title: {
      color: p.onAccent,
      fontFamily: fonts.display,
      fontSize: 28,
      fontWeight: "800",
      marginTop: spacing(0.75),
    },
    subtitle: {
      color: "rgba(255,255,255,0.67)",
      fontSize: 14,
      lineHeight: 21,
      marginTop: spacing(0.75),
      maxWidth: 300,
    },
    metrics: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: spacing(1.25),
      marginTop: spacing(2),
    },
    metric: {
      flexGrow: 1,
      flexBasis: "44%",
      backgroundColor: p.white,
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: p.softBorder,
      padding: spacing(1.75),
      ...shadow.card,
    },
    metricValue: {
      color: p.ink,
      fontFamily: fonts.display,
      fontSize: 24,
      fontWeight: "800",
    },
    metricLabel: {
      color: p.mutedText,
      fontSize: 11,
      fontWeight: "800",
      marginTop: 3,
    },
    section: {
      color: p.ink,
      fontFamily: fonts.display,
      fontSize: 20,
      fontWeight: "800",
      marginTop: spacing(3.5),
      marginBottom: spacing(1.5),
    },
    chart: {
      flexDirection: "row",
      alignItems: "flex-end",
      gap: spacing(0.75),
      height: 150,
      padding: spacing(2),
      backgroundColor: p.white,
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: p.softBorder,
    },
    barWrap: {
      flex: 1,
      height: "100%",
      justifyContent: "flex-end",
      alignItems: "center",
    },
    bar: {
      width: "100%",
      minHeight: 4,
      borderRadius: radius.pill,
      backgroundColor: p.burgundy,
    },
    day: { color: p.mutedText, fontSize: 9, marginTop: 5 },
    list: { gap: spacing(1) },
    row: {
      flexDirection: "row",
      alignItems: "center",
      gap: spacing(1.5),
      backgroundColor: p.white,
      borderRadius: radius.md,
      borderWidth: 1,
      borderColor: p.softBorder,
      padding: spacing(1.75),
    },
    rank: {
      width: 32,
      height: 32,
      borderRadius: radius.sm,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: p.wineTint,
    },
    rankText: { color: p.burgundy, fontWeight: "900" },
    rowCopy: { flex: 1 },
    rowTitle: { color: p.ink, fontSize: 14, fontWeight: "800" },
    rowHint: { color: p.mutedText, fontSize: 11, marginTop: 3 },
    revenue: { color: p.burgundy, fontSize: 13, fontWeight: "900" },
    upgrade: {
      padding: spacing(2),
      borderRadius: radius.md,
      backgroundColor: p.wineTint,
    },
    upgradeTitle: { color: p.ink, fontWeight: "800" },
    upgradeHint: {
      color: p.mutedText,
      fontSize: 12,
      lineHeight: 18,
      marginTop: 4,
    },
    scheduleCard: {
      backgroundColor: p.white,
      borderColor: p.softBorder,
      borderRadius: radius.md,
      borderWidth: 1,
      gap: spacing(1.25),
      padding: spacing(1.75),
      ...shadow.card,
    },
    scheduleHead: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
    },
    scheduleInput: {
      backgroundColor: p.sunken,
      borderColor: p.softBorder,
      borderRadius: radius.sm,
      borderWidth: 1,
      color: p.ink,
      fontFamily: fonts.body,
      fontSize: 14,
      paddingHorizontal: spacing(1.25),
      paddingVertical: spacing(1.2),
    },
    scheduleOptions: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: spacing(0.7),
    },
    scheduleChip: {
      backgroundColor: p.sunken,
      borderRadius: radius.pill,
      paddingHorizontal: spacing(1.2),
      paddingVertical: spacing(0.75),
    },
    scheduleChipActive: { backgroundColor: p.burgundy },
    scheduleChipText: {
      color: p.ink,
      fontFamily: fonts.body,
      fontSize: 11,
      fontWeight: "800",
      textTransform: "capitalize",
    },
    scheduleChipTextActive: { color: p.onAccent },
    scheduleSave: {
      alignItems: "center",
      backgroundColor: p.burgundy,
      borderRadius: radius.pill,
      paddingVertical: spacing(1.2),
    },
    scheduleSaveText: {
      color: p.onAccent,
      fontFamily: fonts.body,
      fontSize: 12,
      fontWeight: "900",
    },
  });
