import { StyleSheet } from "react-native";
import { fonts, radius, shadow, spacing, type Palette } from "../../src/theme";

// eslint-disable-next-line max-lines-per-function -- complete storefront settings palette
export const makeStyles = (p: Palette) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: p.cream },
    content: { padding: spacing(3), paddingBottom: spacing(7) },
    hero: {
      backgroundColor: p.ink,
      borderRadius: radius.lg,
      padding: spacing(2.5),
      overflow: "hidden",
    },
    watermark: { position: "absolute", right: -18, bottom: -24, opacity: 0.08 },
    eyebrow: {
      color: p.gold,
      fontFamily: fonts.body,
      fontSize: 10,
      fontWeight: "900",
      letterSpacing: 1.8,
    },
    title: {
      color: p.onAccent,
      fontFamily: fonts.display,
      fontSize: 27,
      fontWeight: "800",
      marginTop: spacing(0.75),
    },
    subtitle: {
      color: "rgba(255,255,255,0.66)",
      fontFamily: fonts.body,
      fontSize: 14,
      lineHeight: 21,
      marginTop: spacing(0.75),
      maxWidth: 300,
    },
    sectionTitle: {
      color: p.ink,
      fontFamily: fonts.display,
      fontSize: 20,
      fontWeight: "800",
      marginTop: spacing(3.5),
    },
    sectionHint: {
      color: p.mutedText,
      fontFamily: fonts.body,
      fontSize: 13,
      lineHeight: 19,
      marginTop: spacing(0.5),
      marginBottom: spacing(1.5),
    },
    panel: {
      backgroundColor: p.white,
      borderRadius: radius.lg,
      borderWidth: 1,
      borderColor: p.softBorder,
      overflow: "hidden",
      ...shadow.card,
    },
    row: {
      minHeight: 72,
      flexDirection: "row",
      alignItems: "center",
      gap: spacing(1.5),
      padding: spacing(2),
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: p.softBorder,
    },
    rowLast: { borderBottomWidth: 0 },
    icon: {
      width: 40,
      height: 40,
      borderRadius: radius.sm,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: p.wineTint,
    },
    copy: { flex: 1 },
    label: {
      color: p.ink,
      fontFamily: fonts.body,
      fontSize: 15,
      fontWeight: "800",
    },
    hint: {
      color: p.mutedText,
      fontFamily: fonts.body,
      fontSize: 12,
      lineHeight: 17,
      marginTop: 2,
    },
    layouts: { flexDirection: "row", gap: spacing(1) },
    layout: {
      flex: 1,
      alignItems: "center",
      paddingVertical: spacing(1.25),
      borderRadius: radius.pill,
      borderWidth: 1,
      borderColor: p.softBorder,
      backgroundColor: p.white,
    },
    layoutActive: { backgroundColor: p.burgundy, borderColor: p.burgundy },
    layoutText: {
      color: p.ink,
      fontFamily: fonts.body,
      fontSize: 12,
      fontWeight: "800",
      textTransform: "capitalize",
    },
    layoutTextActive: { color: p.onAccent },
    saving: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: spacing(1),
      marginTop: spacing(2),
    },
    savingText: {
      color: p.mutedText,
      fontFamily: fonts.body,
      fontSize: 12,
      fontWeight: "700",
    },
    brandPanel: {
      backgroundColor: p.white,
      borderColor: p.softBorder,
      borderRadius: radius.md,
      borderWidth: 1,
      gap: spacing(1.25),
      padding: spacing(1.75),
      ...shadow.card,
    },
    brandColourRow: {
      alignItems: "center",
      flexDirection: "row",
      gap: spacing(1),
    },
    brandSwatch: {
      borderColor: p.softBorder,
      borderRadius: radius.pill,
      borderWidth: 1,
      height: 38,
      width: 38,
    },
    brandInput: {
      backgroundColor: p.sunken,
      borderColor: p.softBorder,
      borderRadius: radius.sm,
      borderWidth: 1,
      color: p.ink,
      flex: 1,
      fontFamily: fonts.body,
      fontSize: 14,
      paddingHorizontal: spacing(1.25),
      paddingVertical: spacing(1.1),
    },
    brandSave: {
      backgroundColor: p.burgundy,
      borderRadius: radius.pill,
      paddingHorizontal: spacing(1.25),
      paddingVertical: spacing(1.05),
    },
    brandSaveText: {
      color: p.onAccent,
      fontFamily: fonts.body,
      fontSize: 11,
      fontWeight: "900",
    },
    assetRow: { flexDirection: "row", gap: spacing(1) },
    assetButton: {
      alignItems: "center",
      backgroundColor: p.sunken,
      borderColor: p.softBorder,
      borderRadius: radius.sm,
      borderStyle: "dashed",
      borderWidth: 1,
      flex: 1,
      height: 120,
      justifyContent: "center",
      overflow: "hidden",
    },
    assetImage: { height: 82, resizeMode: "cover", width: "100%" },
    assetLabel: {
      color: p.burgundy,
      fontFamily: fonts.body,
      fontSize: 11,
      fontWeight: "800",
      marginTop: spacing(0.5),
    },
    zoneRow: { alignItems: "center", flexDirection: "row", gap: spacing(0.75) },
    zoneRemove: {
      borderColor: p.danger,
      borderRadius: radius.pill,
      borderWidth: 1,
      paddingHorizontal: spacing(0.9),
      paddingVertical: spacing(0.65),
    },
    zoneRemoveText: {
      color: p.danger,
      fontFamily: fonts.body,
      fontSize: 10,
      fontWeight: "800",
    },
    zoneCreate: {
      alignItems: "center",
      flexDirection: "row",
      gap: spacing(0.65),
    },
    zoneName: { flex: 1 },
    zoneFee: { flex: 0, width: 92 },
  });
